data_train:
  dataset1:
    _target_: rainbowneko.train.data.ImageLabelDataset
    _partial_: True # Not directly instantiate the object here. There are other parameters to be added in the runtime.
    batch_size: 4
    loss_weight: 1.0

    source:
      data_source1:
        _target_: rainbowneko.train.data.source.IndexSource
        img_root: 'imgs/train'
        prompt_template: 'prompt_tuning_template/object.txt'
        caption_file: null # path to image captions (file_words)
        att_mask: null
        bg_color: [ 255, 255, 255 ] # RGB; for ARGB -> RGB

        word_names: {}

        text_transforms:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: hcpdiff.utils.caption_tools.TemplateFill
              word_names: ${....word_names}
    bucket:
      _target_: hcpdiff.data.bucket.RatioBucket.from_files # aspect ratio bucket
      target_area: ${hcp.eval:"512*512"}
      num_bucket: 5

data_eval:
  dataset1:
    _target_: rainbowneko.train.data.ImageLabelDataset
    _partial_: True # Not directly instantiate the object here. There are other parameters to be added in the runtime.
    batch_size: 4
    loss_weight: 1.0

    source:
      data_source1:
        _target_: rainbowneko.train.data.source.IndexSource
        img_root: 'imgs/eval'
        prompt_template: 'prompt_tuning_template/object.txt'
        caption_file: null # path to image captions (file_words)
        att_mask: null
        bg_color: [ 255, 255, 255 ] # RGB; for ARGB -> RGB

        word_names: {}

        text_transforms:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: hcpdiff.utils.caption_tools.TemplateFill
              word_names: ${....word_names}
    bucket:
      _target_: hcpdiff.data.bucket.RatioBucket.from_files # aspect ratio bucket
      target_area: ${hcp.eval:"512*512"}
      num_bucket: 5